modLoader="javafml" #mandatory
loaderVersion="[36,)"
license="GNU GPLv3"
issueTrackerURL="https://sorgscraft.unchilled.dev/"
[[mods]]
modId="sorgscraft"
version="1.16.5-0.0.4"
displayName="SorgsCraft"
updateJSONURL="https://sorgscraft.unchilled.dev/updates.json" 
displayURL="https://sorgscraft.unchilled.dev" 
#logoFile="examplemod.png"
credits="Brane Sorgs, Japan, Egotopia, Blossoms, and all the random ass servers in between"
authors="Blythe, unchilled"
description='''
Adds members from the Discord along with special abilities, items, and blocks from the Discord.
'''
[[dependencies.sorgscraft]] #optional
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sorgscraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
